### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by drewfreyling** [postaljs/postal.js#147]
What is the current list of supported browsers for postal.js? Happy to add them to the readme if I know what they are.

**Comment by ifandelse** [comment]
@drewfreyling AFAIK, it should work as far back as IE8 (and it's contemporaries...which amounts to nearly ancient history for what I'm working on these days). My day-to-day stack is in the process of being updated from IE9 to IE11 (all the versions of Chrome, FF and Safari we use haven't given us any issues...focusing on IE in this explanation since it was the problem child back a couple of years ago).
